---
- name: Deploy Professional Hyprland Workstation
  hosts: all
  become: false
  vars:
    ansible_python_interpreter: auto_silent
    user_home: "{{ ansible_facts['env']['HOME'] | default('/home/' + ansible_facts['user_id']) }}"
  roles:
    - workstation